const path = require('path')

// DO NOT EDIT THIS FILE
// instead, rename settings_example.js to settings.js and change the configuration there

module.exports = {
  sizes: [400,1200], // Array of numbers
  // Where to fetch images to resize
  inputDir: path.join(process.cwd(), 'full'), // [cwd]/full
  // Where to save resized images; submaps for every size are created in this location
  outputDir: process.cwd(), // [cwd]
  remoteDir: 'ftp location that should reflect outputDir', // Should be an absolute path
  ftpHost: 'localhost',
  ftpPort: '21',
  ftpUser: 'configure an user',
  ftpPass: 'password for ftpUser',
  templateDir: path.join(__dirname, 'templates'),
  templateDefault: 'full_links.hbs',
}
