const path = require('path')

// DO NOT EDIT THIS FILE
// instead, rename settings_example.js to settings.js and change the configuration there

module.exports = {
  // Where to fetch images to resize
  inputDir: [process.cwd(), 'full'].join(path.sep), // [cwd]/full
  // Where to save resized images; submaps for every size are created in this location
  outputDir: process.cwd(), // [cwd]
}
